### ISSUE TITLE
Sensibly loading forecasted indices

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatSpaceWeather#1]
The forecast files for F10.7 contain a lot of other forecasted indices.  We need to figure out a way to make this data accessible without downloading the file into multiple directories.

**Comment by rstoneback** [comment]
A potential solution:

Create a new instrument file for the data desired, and set the directory_format option so it looks to the F10.7 directory.

Something like

`directory_format = os.path.join(’sw', ‘f107’)`

at the instrument module top level could work.

Cheers.

**Comment by jklenzing** [comment]
Linking to pysat/pysat#614

**Comment by aburrell** [comment]
Thought about this a bit more.  Right now we're rewriting some of the files on download.  Why not rewrite multiple files on download and save them into the correct directories?
