### ISSUE TITLE
MAINT: remove deprecated kp tag: '' 

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatSpaceWeather#101]
# Description
GFZ changed their database, and the old format of files are not available any longer.  The new dataset is of higher quality, and so we will remove support for the old dataset in version 0.2.0+ of pysatSpaceWeather.

**Comment by aburrell** [comment]
The fixes are in on the 'develop' branch.  @hococoder, can confirm that these are the extent of the changes needed? If that fixes all the current problems I can get a bugfix release out.

**Comment by aburrell** [comment]
Did you update your historic tag from ‘’ to ‘def’?

There should have been warnings telling you what was going on, but sometimes settings don’t let you see all of them.  The GFZ database was also updated, and the new tags point to the new database and new files, which are different from the old historic files with the ‘’ tag.



From: Josh Steele ***@***.***>
Reply-To: pysat/pysatSpaceWeather ***@***.***>
Date: Friday, December 9, 2022 at 14:14
To: pysat/pysatSpaceWeather ***@***.***>
Cc: "Burrell, Angeline G CIV USN NRL (7633) Washington DC (USA)" ***@***.***>, Mention ***@***.***>
Subject: Re: [pysat/pysatSpaceWeather] MAINT: remove deprecated kp tag: '' (Issue #101)


@aburrell<https://github.com/aburrell> just a heads up - instead of just updating the affected code, i upgraded to 0.0.8 and now am having major issues downloading kp data. Is this a known potential issue? I will try to get a issue filed once I get to a stopping point with what I am working on

**Comment by hococoder** [comment]
I didn't see any warnings, and this wasn't for historic, but recent data.  I'll file an issue when I can since this sounds like something unique
