### ISSUE TITLE
Check standard docs for pysatSpaceWeather

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatSpaceWeather#113]
There is now a central repository for templates at https://github.com/pysat/pysatEcosystem_Template

- [x] Make sure current issues / actions / etc are up to standard
- [x] Make sure any extra bits here are captured in the templates

**Comment by aburrell** [comment]
Know issue: missing a colon on the questions template.

**Comment by aburrell** [comment]
Known issue: README minimum version needs to be updated.
