### ISSUE TITLE
BUG: NOAA radio flux failure

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatSpaceWeather#126]
# Description
Running the historic noaa flux past the limit no longer yields a dict with the expected key.

# To Reproduce this bug:
After running unit tests, we see
```
FAILED pysatSpaceWeather/tests/test_instruments.py::TestSWInstrumentLogging::test_historic_download_past_limit - KeyError: 'noaa_radio_flux'
```
This appears in the main branch on github actions as well as develop when running locally

## Test configuration
 - OS: Monterrey
 - Version python 3.10.9
 - pysat develop

# Additional context
Running code manually, req.txt yields  '{"": {\n}}\n'

**Comment by aburrell** [comment]
This is a change in behaviour on LASP's end.  Making a fix for it.
