### ISSUE TITLE
BUG: sw_ace was deleted

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatSpaceWeather#13]
At some point after the sw_ace branch was merged into develop, the sw_ace instrument was deleted.  Not sure how to fix this.

**Comment by rstoneback** [comment]
I pushed the copy of sw_ace.py I have to a new branch, sw_ace_rs.

I’ll be out for an hour or so but back on pysat and IVM stuff after. Cheers.

On Oct 22, 2020, at 9:12 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:



Assigned #13<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpysat%2FpysatSpaceWeather%2Fissues%2F13&data=04%7C01%7Crstoneba%40utdallas.edu%7C514d324d247a43c33ce908d87694759e%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637389727287511340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uv2w3PTm%2FHS%2F2CJqvSluqTnqLBfu%2Bw4DIy3yJbZ6kv4%3D&reserved=0> to @rstoneback<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frstoneback&data=04%7C01%7Crstoneba%40utdallas.edu%7C514d324d247a43c33ce908d87694759e%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637389727287511340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=76K1c%2BD4TPVopBDxQg4Y%2FG1rHDTnif4feogzDPQKz5E%3D&reserved=0>.
