### ISSUE TITLE
DOC: Need Space Weather tutorials

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatSpaceWeather#2]
We should add a page to the documentation describing the space weather methods for accessing / comparing indices, as well as one for the model_utils tools.

**Comment by aburrell** [comment]
There aren't any ACE or Dst methods at the moment.  Didn't see much point in doing an example yet.  Should we close this with the completion of #85 ?

**Comment by aburrell** [comment]
Found an ACE method and added an example to #85.  Now just missing Dst.
