### ISSUE TITLE
BUG: sw_ace platform 

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatSpaceWeather#39]
# Description
The ACE platform is wrong.  Instead of `sw` it should be `swpc` because it retrieves the space weather prediction center ACE data.

# To Reproduce this bug

Go read the sw_ace.py docstring

# Additional context
chose `sw` initially, because I couldn't figure out an appropriate platform name.

**Comment by aburrell** [comment]
@jklenzing thoughts?

**Comment by jklenzing** [comment]
That sounds good to me.

**Comment by jklenzing** [comment]
Assuming it only comes from one source.  The other sw products seem to all come from multiple sources.

**Comment by aburrell** [comment]
Further thoughts:
- sw_dst -> dcei_dst

This one is more controversial, if there are other sources of Dst.

**Comment by aburrell** [comment]
these ACE products all have one source.  The scientific ACE data would not be a part of this package, so I think it's good.  Dst is the other instrument that only has one source, but not sure if that could change in the future.

**Comment by aburrell** [comment]
I ended up taking a different tack for ACE, but I am happy with it now!
