### ISSUE TITLE
BUG: download error for days past end of database

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatSpaceWeather#87]
# Description
The historic F10.7 data base will raise a JSON error if you ask for a time when they don't have data.

# To Reproduce this bug:
```
import pysat
from pysatSpaceWeather.instruments import sw_f107

f107_hist = pysat.Instrument(inst_module=sw_f107, tag='historic')
f107_hist.download(start=f107_hist.lasp_stime, stop=f107_hist.today(), freq='MS')
```

## Test configuration
 - OS: OS Big Sur
 - Version: Python 3.9
 - Other details about your setup that could be relevant

# Possible solutions
1) Consider this a feature, since it's clear nothing has been downloaded
2) And an end date attribute to the Instrument (similar to the `lasp_stime` attribute)
3) Something else?

**Comment by jklenzing** [comment]
just pushed a new branch with a possible solution: f107_patch

downstream of #85
