### ISSUE TITLE
MAINT: Kp update

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatSpaceWeather#89]
# Description
Kp data has moved location to: https://kp.gfz-potsdam.de/en/

# To Reproduce this bug:
Not sure if anything is broken yet, but it probably will be in the future.

## Test configuration
N/A

# Additional context
Found from CEDAR announcement.

**Comment by jklenzing** [comment]
It looks like there is now https support, which means we can drop ftp downlods for this instrument.
