### ISSUE TITLE
BUG/TST: combine methods failing for forecast instruments

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatSpaceWeather#9]
**Expected behavior**
The tests for `TestSwKpCombine` and `TestSF107Combine` file point to a directory of archived test data, since some of these depend on FTP access for the latest tests.  The test date should grab the archive date (3-18-209) rather than the latest date for forecasted data.

**Actual behavior**
The test is searching for the latest data.
```
E   FileNotFoundError: [Errno 2] No such file or directory: '/Users/jklenzin/code/core/pysatSpaceWeather/pysatSpaceWeather/tests/test_data/sw/f107/all/f107_1947_to_2020-09-30.txt'
```

**Comment by jklenzing** [comment]
As of ~two months ago (last push to develop), this was working.  Potentially related to changes in pysat or one of the other dependencies.

**Comment by aburrell** [comment]
@jklenzing is this fixed?

**Comment by jklenzing** [comment]
This still fails in develop, but is working in the `pysat_upstream_updates` branch
